version: "3.8"
services:
    db:
        image: mysql
        container_name: db_ustube
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - ustube

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_ustube
        restart: always
        depends_on:
            - db
        ports:
            - "$PMA_PORT:80"
        environment:
            PMA_HOST: db
        networks:
            - ustube

    php:
        build: php
        container_name: php_ustube
        ports:
          - "$PHP_PORT:80"
        volumes:
            - ./php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www/ustube
        restart: always
        networks:
            - ustube

networks:
    ustube:

volumes:
    db-data: